# Generated by Django 4.2.7 on 2025-03-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermoodhistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermoodhistory',
            name='mood',
            field=models.CharField(max_length=100),
        ),
    ]
