# Generated by Django 4.2.7 on 2025-03-18 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_delete_moodhistory'),
        ('users', '0003_update_mood_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermoodhistory',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moods.mood'),
        ),
        migrations.AlterField(
            model_name='usermoodhistory',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moods.mood'),
        ),
    ]
