# Generated by Django 4.2.7 on 2025-03-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_created_at_usermoodhistory_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoodhistory',
            name='track_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
