# Generated by Django 4.2.7 on 2025-03-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_moodhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodHistory',
        ),
    ]
