# Generated by Django 4.2.7 on 2025-03-23 17:25

from django.db import migrations, models
from django.utils.text import slugify


def add_slugs(apps, schema_editor):
    Mood = apps.get_model('moods', 'Mood')
    for index, mood in enumerate(Mood.objects.all()):
        # Create a unique slug by adding index to ensure uniqueness
        base_slug = slugify(mood.name)
        if mood.language_specific and mood.language:
            base_slug = f"{base_slug}-{mood.language}"
        else:
            # Add index to ensure uniqueness for records with same name
            base_slug = f"{base_slug}-{index}"
        mood.slug = base_slug
        mood.save()


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_delete_moodhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='quick_access',
            new_name='language_specific',
        ),
        migrations.AddField(
            model_name='mood',
            name='category',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('relaxed', 'Relaxed'), ('romantic', 'Romantic'), ('angry', 'Angry'), ('nostalgic', 'Nostalgic'), ('lonely', 'Lonely'), ('hopeful', 'Hopeful'), ('peaceful', 'Peaceful'), ('melancholic', 'Melancholic'), ('confident', 'Confident'), ('party', 'Party'), ('devotional', 'Devotional'), ('patriotic', 'Patriotic'), ('festive', 'Festive')], default='happy', max_length=20),
        ),
        migrations.AddField(
            model_name='mood',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='mood',
            name='language',
            field=models.CharField(blank=True, choices=[('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam'), ('punjabi', 'Punjabi'), ('marathi', 'Marathi'), ('bengali', 'Bengali'), ('gujarati', 'Gujarati'), ('english', 'English')], max_length=20, null=True),
        ),
        # First add slug field without the unique constraint
        migrations.AddField(
            model_name='mood',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
        # Add the data migration to populate slugs
        migrations.RunPython(add_slugs),
        # Then update the field to add the unique constraint
        migrations.AlterField(
            model_name='mood',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='mood_icons/'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
